version: '3'
services:
  home:
    build: ./packages/home
    entrypoint: sh -c 'yarn && yarn dev'
    ports:
      - "3000:3000"
    environment:
      - BLOG_URL=http://blog:3000
    volumes:
       - ./packages/home/:/home/node/app
       
  blog:
    build: ./packages/blog
    entrypoint: sh -c 'yarn && yarn dev'
    ports:
      - "3001:3000"
    volumes:
       - ./packages/blog/:/home/node/app

  docs:
    build: ./packages/docs
    entrypoint: sh -c 'yarn && yarn dev'
    ports:
      - "3002:3000"
    volumes:
       - ./packages/docs/:/home/node/app