import Link from 'next/link'
import Head from 'next/head'

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create Blog" />
      </Head>
      <h3>This is our blog</h3>
      <ul>
        <li>
          <Link href="/post/1">
            <a>Post 1</a>
          </Link>
        </li>
        <li>
          <Link href="/post/2">
            <a>Post 2</a>
          </Link>
        </li>
      </ul>
      <a href="/">Home</a>
    </div>
  )
}